import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import nodemailer from "nodemailer";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware to parse JSON and urlencoded requests with generous limits for attachments
  app.use(express.json({ limit: "15mb" }));
  app.use(express.urlencoded({ limit: "15mb", extended: true }));

  // API Route: Handle Job Application
  app.post("/api/apply", async (req, res) => {
    try {
      const { fullName, email, phone, highestEducation, jobTitle, fileData, filename } = req.body;

      if (!fullName || !email || !jobTitle) {
        return res.status(400).json({ 
          success: false, 
          message: "Full Name, Email, and Job Title are required fields." 
        });
      }

      console.log(`[Job Application Received] Position: "${jobTitle}" | Applicant: ${fullName} <${email}>`);

      const destinationEmail = "it.test@telanlaw.com";

      // Formulate the rich HTML body of the email
      const htmlBody = `
        <div style="font-family: 'Inter', system-ui, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; rounded-lg: 16px; background-color: #fafafa;">
          <div style="text-align: center; border-bottom: 2px solid #003366; padding-bottom: 16px; margin-bottom: 24px;">
            <h1 style="color: #003366; margin: 0; font-size: 24px;">New Job Application</h1>
            <p style="color: #bfa15f; margin: 4px 0 0 0; text-transform: uppercase; letter-spacing: 1.5px; font-size: 11px; font-weight: bold;">Telan Solutions Recruitment</p>
          </div>
          
          <div style="margin-bottom: 24px;">
            <p style="font-size: 15px; color: #334155; line-height: 1.6;">You have received a new application for the <strong>${jobTitle}</strong> position.</p>
          </div>

          <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px; background-color: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e2e8f0;">
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 16px; font-weight: bold; color: #1e293b; width: 40%; background-color: #f8fafc; font-size: 14px;">Full Name</td>
              <td style="padding: 12px 16px; color: #475569; font-size: 14px;">${fullName}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 16px; font-weight: bold; color: #1e293b; background-color: #f8fafc; font-size: 14px;">Email Address</td>
              <td style="padding: 12px 16px; color: #475569; font-size: 14px;"><a href="mailto:${email}" style="color: #003366; text-decoration: none;">${email}</a></td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="padding: 12px 16px; font-weight: bold; color: #1e293b; background-color: #f8fafc; font-size: 14px;">Phone Number</td>
              <td style="padding: 12px 16px; color: #475569; font-size: 14px;">${phone || "N/A"}</td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #1e293b; background-color: #f8fafc; font-size: 14px;">Highest Education</td>
              <td style="padding: 12px 16px; color: #475569; font-size: 14px;">${highestEducation || "N/A"}</td>
            </tr>
          </table>

          ${filename ? `
          <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; padding: 12px 16px; border-radius: 8px; margin-bottom: 24px; display: flex; align-items: center;">
            <span style="font-size: 18px; margin-right: 8px;">📄</span>
            <span style="font-size: 13px; color: #166534; font-weight: 500;">
              <strong>Attached Resume:</strong> ${filename}
            </span>
          </div>
          ` : ""}

          <div style="border-top: 1px solid #e2e8f0; padding-top: 16px; text-align: center; font-size: 11px; color: #94a3b8;">
            This security notification was automatically generated by Telan Solutions Careers Portal.<br/>
            Target destination email: ${destinationEmail}
          </div>
        </div>
      `;

      // Check if SMTP settings are configured
      const smtpHost = process.env.SMTP_HOST;
      const smtpPort = process.env.SMTP_PORT;
      const smtpUser = process.env.SMTP_USER;
      const smtpPass = process.env.SMTP_PASS;
      const smtpFrom = process.env.SMTP_FROM || `"Telan Careers Portal" <it.test@telanlaw.com>`;

      const attachments = fileData && filename 
        ? [{
            filename: filename,
            content: fileData.split("base64,")[1] || fileData,
            encoding: "base64"
          }]
        : [];

      if (smtpHost && smtpUser && smtpPass) {
        // Create full authenticated transport
        const transporter = nodemailer.createTransport({
          host: smtpHost,
          port: parseInt(smtpPort || "587"),
          secure: smtpPort === "465", // true for 465, false for other ports
          auth: {
            user: smtpUser,
            pass: smtpPass
          }
        });

        // Send real email
        const info = await transporter.sendMail({
          from: smtpFrom,
          to: destinationEmail,
          subject: `[Job Application] ${fullName} - ${jobTitle}`,
          html: htmlBody,
          attachments: attachments
        });

        console.log(`[Email Sent Success] MessageID: ${info.messageId}`);
        return res.json({ 
          success: true, 
          message: "Application submitted and sent to it.test@telanlaw.com successfully!" 
        });
      } else {
        // Fallback for development / preview mode
        console.warn("\n==================================================");
        console.warn("⚠️ SMTP credentials not fully configured in your .env secrets.");
        console.warn("   To enable real email delivery directly to it.test@telanlaw.com, please add:");
        console.warn("   - SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM inside your secrets.");
        console.warn("--------------------------------------------------");
        console.warn(`📩 EMAIL DESTINATION: ${destinationEmail}`);
        console.warn(`📝 SUBJECT: [Job Application] ${fullName} - ${jobTitle}`);
        console.warn(`👤 APPLICANT: ${fullName} (${email})`);
        console.warn(`📱 PHONE: ${phone}`);
        console.warn(`🎓 EDUCATION: ${highestEducation}`);
        console.warn(`📄 ATTACHED FILE: ${filename || "None"}`);
        console.warn("==================================================\n");

        return res.json({
          success: true,
          message: "Form accepted! (Simulated dispatch to 123@xywtos.com completed successfully.)",
          simulated: true,
          details: {
            destination: destinationEmail,
            subject: `[Job Application] ${fullName} - ${jobTitle}`,
            applicant: { fullName, email, phone, highestEducation }
          }
        });
      }
    } catch (error: any) {
      console.error("[Email Error Handler]", error);
      return res.status(500).json({ 
        success: false, 
        message: "Failed to process application delivery.", 
        error: error.message 
      });
    }
  });

  // Serve static assets or mount Vite Developer server
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is booted up and running on port ${PORT}`);
  });
}

startServer();
